before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: steveh
      name: homebrew-custom
    homepage: "https://github.com/steveh/telegraf-exec-fronius"
    description: "Extract Fronius solar data and output Influx line protocol"
    folder: Formula
    commit_author:
      name: goreleaserbot
      email: goreleaser@kotiri.com
